name: Auto Sync Fork

on:
  push:
    branches:
      - main
  workflow_dispatch: # Permite execução manual

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout o repositório fork
      - name: Checkout Fork
        uses: actions/checkout@v3

      # Adicionar o repositório original como upstream
      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/Ana-Teste/reactTeste.git
          git fetch upstream

      # Mesclar mudanças do repositório original no fork
      - name: Merge Changes Ignoring 'public' and '.env'
        run: |
          # Atualizar com as alterações do upstream
          git pull upstream main --no-commit --no-ff
          
          # Remover a pasta public e o arquivo .env
          rm -rf public
          rm -f .env

          # Confirmar as alterações sem incluir os arquivos removidos
          git add .
          git commit -m "Sync with upstream, ignoring public and .env"
          
          # Empurrar as alterações para o fork
